---
kind: pipeline
name: mon-super-pipeline-ci

steps:
  - name: hello-world
    image: lowess/preact-cli
    commands:
      - echo 'Hello World'

  - name: create-template
    image: lowess/preact-cli
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} test_ci

  - name: node-install
    image: lowess/preact-cli
    commands:
      - cd test_ci
      - npm install

  - name: node-build
    image: lowess/preact-cli
    commands:
      - cd test_ci
      - npm run build

  - name: node-preview
    image: lowess/preact-cli
    commands:
      - cd test_ci
      - npm run build:preview

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: drone-slack
      channel : drone-ci
      template: >
        {{#success build.status}}
          Bravo la build {{build.number}} a reussi. Alexis Taupin
        {{else}}
          Eh bah nan, la build {{build.number}} est kc. Alexis Taupin
        {{\success}}